apiVersion: {{ .Values.apiVersion }}
kind: Deployment
metadata:
  name: {{ template "imgproxy.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "imgproxy.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "imgproxy.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "imgproxy.fullname" . }}
        release: {{ .Release.Name | quote }}
{{- if .Values.annotations }}
      annotations:
        {{- range $key, $value := .Values.annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
{{- end }}
    spec:
    {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: "{{ .Release.Name }}-docker-registry-secret"
{{- end }}
      containers:
      - name: "imgproxy"
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: IMGPROXY_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "imgproxy.fullname" . }}-secrets
              key: key
        - name: IMGPROXY_SALT
          valueFrom:
            secretKeyRef:
              name: {{ template "imgproxy.fullname" . }}-secrets
              key: salt
        - name: IMGPROXY_SIGNATURE_SIZE
          value: {{ .Values.signatureSize }}
        - name: IMGPROXY_READ_TIMEOUT
          value: "{{ .Values.readTimeout }}"
        - name: IMGPROXY_WRITE_TIMEOUT
          value: "{{ .Values.writeTimeout }}"
        - name: IMGPROXY_KEEP_ALIVE_TIMEOUT
          value: "{{ .Values.keepAliveTimeout }}"
        - name: IMGPROXY_DOWNLOAD_TIMEOUT
          value: "{{ .Values.downloadTimeout }}"
        {{- if .Values.concurrency }}
        - name: IMGPROXY_CONCURRENCY
          value: "{{ .Values.concurrency }}"
        {{- end }}
        {{- if .Values.maxClients }}
        - name: IMGPROXY_MAX_CLIENTS
          value: "{{ .Values.maxClients }}"
        {{- end }}
        - name: IMGPROXY_TTL
          value: "{{ .Values.ttl }}"
        {{- if .Values.soReuseport }}
        - name: IMGPROXY_SO_REUSEPORT
          value: "true"
        {{- end }}
        {{- if .Values.userAgent }}
        - name: IMGPROXY_USER_AGENT
          value: "{{ .Values.userAgent }}"
        {{- end }}
        {{- if .Values.useEtag }}
        - name: IMGPROXY_USE_ETAG
          value: "true"
        {{- end }}
        {{- if .Values.localFileSystemRoot }}
        - name: IMGPROXY_LOCAL_FILESYSTEM_ROOT
          value: "{{ .Values.localFileSystemRoot }}"
        {{- end }}
        - name: IMGPROXY_MAX_SRC_RESOLUTION
          value: "{{ .Values.maxSrcResolution }}"
        - name: IMGPROXY_MAX_SRC_FILE_SIZE
          value: "{{ .Values.maxSrcFileSize }}"
        - name: IMGPROXY_MAX_ANIMATION_FRAMES
          value: "{{ .Values.maxAnimationFrames }}"
        {{- if .Values.secret }}
        - name: IMGPROXY_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "imgproxy.fullname" . }}-secrets
              key: secret
        {{- end }}
        {{- if .Values.allowOrigin }}
        - name: IMGPROXY_ALLOW_ORIGIN
          value: "{{ .Values.allowOrigin }}"
        {{- end }}
        {{- if .Values.allowedSources }}
        - name: IMGPROXY_ALLOWED_SOURCES
          value: "{{ .Values.allowedSources }}"
        {{- end }}
        {{- if .Values.ignoreSslVerification}}
        - name: IMGPROXY_IGNORE_SSL_VERIFICATION
          value: "true"
        {{- end }}
        {{- if .Values.developmentErrorsMode }}
        - name: IMGPROXY_DEVELOPMENT_ERRORS_MODE
          value: "true"
        {{- end }}
        - name: IMGPROXY_QUALITY
          value: "{{ .Values.quality }}"
        - name: IMGPROXY_GZIP_COMPRESSION
          value: "{{ .Values.gzipCompression }}"
        {{- if .Values.jpegProgressive}}
        - name: IMGPROXY_JPEG_PROGRESSIVE
          value: "true"
        {{- end }}
        {{- if .Values.jpegNoSubsample }}
        - name: IMGPROXY_JPEG_NO_SUBSAMPLE
          value: "true"
        {{- end }}
        {{- if .Values.jpegTrellisQuant }}
        - name: IMGPROXY_JPEG_TRELLIS_QUANT
          value: "true"
        {{- end }}
        {{- if .Values.jpegOvershootDeringing }}
        - name: IMGPROXY_JPEG_OVERSHOOT_DERINGING
          value: "true"
        {{- end }}
        {{- if .Values.jpegOptimizeScans }}
        - name: IMGPROXY_JPEG_OPTIMIZE_SCANS
          value: "true"
        {{- end }}
        {{- if .Values.jpegQuantTable }}
        - name: IMGPROXY_JPEG_QUANT_TABLE
          value: "{{ .Values.jpegQuantTable }}"
        {{- end }}
        {{- if .Values.pngInterlaced }}
        - name: IMGPROXY_PNG_INTERLACED
          value: "true"
        {{- end }}
        {{- if .Values.pngQuantize }}
        - name: IMGPROXY_PNG_QUANTIZE
          value: "true"
        {{- end }}
        - name: IMGPROXY_PNG_QUANTIZATION_COLORS
          value: "{{ .Values.pngQuantizationColors }}"
        {{- if .Values.enableWebpDetection }}
        - name: IMGPROXY_ENABLE_WEBP_DETECTION
          value: "true"
        {{- end }}
        {{- if .Values.enforceWebp }}
        - name: IMGPROXY_ENFORCE_WEBP
          value: "true"
        {{- end }}
        {{- if .Values.enableClientHints }}
        - name: IMGPROXY_ENABLE_CLIENT_HINTS
          value: "true"
        {{- end }}
        {{- if .Values.watermarkData }}
        - name: IMGPROXY_WATERMARK_DATA
          value: "{{ .Values.watermarkData }}"
        {{- end }}
        {{- if .Values.watermarkPath }}
        - name: IMGPROXY_WATERMARK_PATH
          value: "{{ .Values.watermarkPath }}"
        {{- end }}
        {{- if .Values.watermarkUrl }}
        - name: IMGPROXY_WATERMARK_URL
          value: "{{ .Values.watermarkUrl }}"
        {{- end }}
        - name: IMGPROXY_WATERMARK_OPACITY
          value: "{{ .Values.watermarkOpacity }}"
        - name: IMGPROXY_WATERMARK_CACHE_SIZE
          value: "{{ .Values.watermarkCacheSize }}"
        {{- if .Values.presets }}
        - name: IMGPROXY_PRESETS
          value: "{{ .Values.presets }}"
        {{- end }}
        {{- if .Values.onlyPresets }}
        - name: IMGPROXY_ONLY_PRESETS
          value: "true"
        {{- end }}

        {{- if .Values.useS3 }}
        - name: IMGPROXY_USE_S3
          value: "true"
        {{- if .Values.awsKey }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "imgproxy.fullname" . }}-secrets
              key: awsKey
        {{- end }}
        {{- if .Values.awsSecret }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "imgproxy.fullname" . }}-secrets
              key: awsSecret
        {{- end }}
        - name: IMGPROXY_S3_REGION
          value: "{{ .Values.awsRegion }}"
        - name: IMGPROXY_S3_ENDPOINT
          value: "{{ .Values.s3Endpoint }}"
        {{- end }}

        {{- if .Values.gcsKey }}
        - name: IMGPROXY_GCS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "imgproxy.fullname" . }}-secrets
              key: gcsKey
        {{- end }}

        {{- if .Values.newRelicKey }}
        - name: IMGPROXY_NEW_RELIC_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "imgproxy.fullname" . }}-secrets
              key: newRelicKey
        - name: IMGPROXY_NEW_RELIC_APP_NAME
          value: "{{ .Values.newRelicAppName }}"
        {{- end }}

        {{- if .Values.enablePrometheus }}
        - name: IMGPROXY_PROMETHEUS_BIND
          value: ":8081"
        {{- end }}

        {{- if .Values.bugsnagKey }}
        - name: IMGPROXY_BUGSNAG_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "imgproxy.fullname" . }}-secrets
              key: bugsnagKey
        - name: IMGPROXY_BUGSNAG_STAGE
          value: "{{ .Values.bugsnagStage }}"
        {{- end }}

        {{- if .Values.honeybadgerKey }}
        - name: IMGPROXY_HONEYBADGER_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "imgproxy.fullname" . }}-secrets
              key: honeybadgerKey
        - name: IMGPROXY_HONEYBADGER_ENV
          value: "{{ .Values.honeybadgerEnv }}"
        {{- end }}

        {{- if .Values.sentryDsn }}
        - name: IMGPROXY_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: {{ template "imgproxy.fullname" . }}-secrets
              key: sentryDsn
        - name: IMGPROXY_SENTRY_ENVIRONMENT
          value: "{{ .Values.sentryEnvironment }}"
        {{- if .Values.sentryRelease }}
        - name: IMGPROXY_SENTRY_RELEASE
          value: "{{ .Values.sentryRelease }}"
        {{- end }}
        {{- end }}

        {{- if .Values.reportDownloadingErrors }}
        - name: IMGPROXY_REPORT_DOWNLOADING_ERRORS
          value: "true"
        {{- end }}

        - name: IMGPROXY_LOG_FORMAT
          value: "{{ .Values.logFormat }}"
        - name: IMGPROXY_LOG_LEVEL
          value: "{{ .Values.logLevel }}"
        {{- if .Values.syslogEnable }}
        - name: IMGPROXY_SYSLOG_ENABLE
          value: "true"
        - name: IMGPROXY_SYSLOG_LEVEL
          value: "{{ .Values.syslogLevel }}"
        - name: IMGPROXY_SYSLOG_NETWORK
          value: "{{ .Values.syslogNetwork }}"
        {{- if .Values.syslogAddress }}
        - name: IMGPROXY_SYSLOG_ADDRESS
          value: "{{ .Values.syslogAddress }}"
        {{- end }}
        - name: IMGPROXY_SYSLOG_TAG
          value: "{{ .Values.syslogTag }}"
        {{- end }}

        - name: IMGPROXY_DOWNLOAD_BUFFER_SIZE
          value: "{{ .Values.downloadBufferSize }}"
        - name: IMGPROXY_GZIP_BUFFER_SIZE
          value: "{{ .Values.gzipBufferSize }}"
        - name: IMGPROXY_FREE_MEMORY_INTERVAL
          value: "{{ .Values.freeMemoryInterval }}"
        - name: IMGPROXY_BUFFER_POOL_CALIBRATION_THRESHOLD
          value: "{{ .Values.bufferPoolCalibrationThreshold }}"

        {{- if .Values.baseUrl }}
        - name: IMGPROXY_BASE_URL
          value: "{{ .Values.baseUrl }}"
        {{- end }}
        {{- if .Values.useLinearColorspace }}
        - name: IMGPROXY_USE_LINEAR_COLORSPACE
          value: "true"
        {{- end }}
        {{- if .Values.disableShrinkOnLoad }}
        - name: IMGPROXY_DISABLE_SHRINK_ON_LOAD
          value: "true"
        {{- end }}
        {{- if .Values.applyUnsharpenMasking }}
        - name: IMGPROXY_APPLY_UNSHARPEN_MASKING
          value: "true"
        {{- end }}
        {{- if .Values.stripMetadata }}
        - name: IMGPROXY_STRIP_METADATA
          value: "true"
        {{- end }}

        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
            httpHeaders:
            - name: Authorization
              value: Bearer {{ .Values.secret }}
          {{- with .Values.readinessProbe }}
          initialDelaySeconds: {{ .initialDelaySeconds | default 10 }}
          timeoutSeconds: {{ .timeoutSeconds | default 5}}
          successThreshold: {{ .successThreshold | default 1 }}
          failureThreshold: {{ .failureThreshold | default 5 }}
          {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
            httpHeaders:
            - name: Authorization
              value: Bearer {{ .Values.secret }}
          {{- with .Values.livenessProbe }}
          initialDelaySeconds: {{ .initialDelaySeconds | default 50 }}
          timeoutSeconds: {{ .timeoutSeconds | default 5}}
          successThreshold: {{ .successThreshold | default 1 }}
          failureThreshold: {{ .failureThreshold | default 5 }}
          {{- end }}
