{{- if .Values.imagePullSecrets }}
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imgproxy.imagePullSecrets" . }}
kind: Secret
metadata:
  labels: {{ include "imgproxy.labels" . | nindent 4 }}
  name: "{{ .Release.Name }}-docker-registry-secret"
type: kubernetes.io/dockerconfigjson
{{- end }}
