{{- if and .Values.ingress.enabled .Values.ingress.health.whitelist -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "imgproxy.fullname" . }}-health
  labels:
    app: {{ template "imgproxy.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.health.whitelist }}
{{- if .Values.ingress.health.annotations }}
{{ toYaml .Values.ingress.health.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.tls.enabled }}
  tls:
  {{- range := .Values.ingress.health.tls}}
  - hosts:
    {{- range := .hosts}}
    - {{ . }}
    {{- end }}
    secretName: {{ .secretName | default (printf "%s-health-tls" (include "imgproxy.fullname" .)) | quote }}
  {{- end}}
{{- end }}
  rules:
  {{- range := .Values.ingress.health.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /health
        backend:
          serviceName: {{ template "imgproxy.fullname" . }}
          servicePort: 80
  {{- end}}
{{- end -}}
