{{- if .Values.ingress.enabled -}}
{{- $dot := . }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "imgproxy.fullname" . }}
  labels:
    app: {{ template "imgproxy.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if or .Values.ingress.annotations (and .Values.ingress.tls.enabled .Values.ingress.acme) }}
  annotations:
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
{{- if and .Values.ingress.tls.enabled .Values.ingress.acme }}
    kubernetes.io/tls-acme: "true"
{{- end }}
{{- end }}
spec:
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "imgproxy.fullname" .)) | quote }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ template "imgproxy.fullname" $dot }}
              servicePort: {{ $.Values.servicePort }}
        {{- end }}
  {{- end }}
{{- end -}}
