apiVersion: v1
kind: Service
metadata:
  name: {{ template "imgproxy.fullname" . }}
  labels: {{ include "imgproxy.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ template "imgproxy.fullname" . }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 8081
    protocol: TCP
    targetPort: 8081
  type: {{ default "ClusterIP" .Values.serviceType }}
