{{- with .Values.features.aws }}
{{- if (and .enabled .iamRoleName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "imgproxy.fullname" $ }}-service-account
  annotations:
    {{ include "aws.iamRoleAnnotation" $ }}
{{- end }}
{{- end }}